# 改前缀为 Ctrl+a（解放左手，更顺手）
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 窗口/窗格索引从 1 开始（更符合直觉）
set -g base-index 1
set -g pane-base-index 1

# 鼠标、剪贴板、历史
set -g mouse on
set -g set-clipboard on
set -g history-limit 50000

# 分屏快捷键
bind-key - split-window -v
bind-key | split-window -h

# hjkl 切窗格
bind-key j select-pane -L
bind-key k select-pane -D
bind-key i select-pane -U
bind-key l select-pane -R

# 重命名
bind-key r command-prompt "rename-window '%%'"    # 重命名窗口
bind-key R command-prompt "rename-session '%%'"   # 重命名会话

# ---------- 插件（resurrect） ----------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# 插件管理器（必须最后一行）
run '~/.tmux/plugins/tpm/tpm'
